<?php if (isset($component)) { $__componentOriginal9ac128a9029c0e4701924bd2d73d7f54 = $component; } ?>
<?php if (isset($attributes)) { $__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54 = $attributes; } ?>
<?php $component = App\View\Components\AppLayout::resolve([] + (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag ? $attributes->all() : [])); ?>
<?php $component->withName('app-layout'); ?>
<?php if ($component->shouldRender()): ?>
<?php $__env->startComponent($component->resolveView(), $component->data()); ?>
<?php if (isset($attributes) && $attributes instanceof Illuminate\View\ComponentAttributeBag): ?>
<?php $attributes = $attributes->except(\App\View\Components\AppLayout::ignoredParameterNames()); ?>
<?php endif; ?>
<?php $component->withAttributes([]); ?>
     <?php $__env->slot('header', null, []); ?> Healthcare Reports <?php $__env->endSlot(); ?>

    <?php $tid = auth()->user()->tenant_id; ?>

    
    <div class="bg-white dark:bg-[#1e293b] rounded-2xl border border-gray-200 dark:border-white/10 mb-6">
        <div class="p-4">
            <form method="GET" class="flex flex-col lg:flex-row gap-3">
                <select name="report_type"
                    class="px-3 py-2 text-sm rounded-xl border border-gray-200 dark:border-white/10 bg-gray-50 dark:bg-[#0f172a] text-gray-900 dark:text-white">
                    <option value="">Semua Report</option>
                    <option value="patient_statistics" <?php if(request('report_type') === 'patient_statistics'): echo 'selected'; endif; ?>>Patient Statistics</option>
                    <option value="revenue_report" <?php if(request('report_type') === 'revenue_report'): echo 'selected'; endif; ?>>Revenue Report</option>
                    <option value="department_performance" <?php if(request('report_type') === 'department_performance'): echo 'selected'; endif; ?>>Department Performance</option>
                    <option value="doctor_productivity" <?php if(request('report_type') === 'doctor_productivity'): echo 'selected'; endif; ?>>Doctor Productivity</option>
                    <option value="inventory_status" <?php if(request('report_type') === 'inventory_status'): echo 'selected'; endif; ?>>Inventory Status</option>
                </select>
                <div>
                    <input type="date" name="from" value="<?php echo e(request('from')); ?>"
                        class="px-3 py-2 text-sm rounded-xl border border-gray-200 dark:border-white/10 bg-gray-50 dark:bg-[#0f172a] text-gray-900 dark:text-white"
                        placeholder="Dari Tanggal">
                </div>
                <div>
                    <input type="date" name="to" value="<?php echo e(request('to')); ?>"
                        class="px-3 py-2 text-sm rounded-xl border border-gray-200 dark:border-white/10 bg-gray-50 dark:bg-[#0f172a] text-gray-900 dark:text-white"
                        placeholder="Sampai Tanggal">
                </div>
                <button type="submit" class="px-4 py-2 text-sm bg-blue-600 text-white rounded-xl hover:bg-blue-700">
                    Filter
                </button>
                <div class="flex items-end gap-2">
                    <button type="button" onclick="exportReport('pdf')"
                        class="px-4 py-2 text-sm bg-red-600 text-white rounded-xl hover:bg-red-700">
                        Export PDF
                    </button>
                    <button type="button" onclick="exportReport('excel')"
                        class="px-4 py-2 text-sm bg-green-600 text-white rounded-xl hover:bg-green-700">
                        Export Excel
                    </button>
                </div>
            </form>
        </div>
    </div>

    
    <div class="bg-white dark:bg-[#1e293b] rounded-2xl border border-gray-200 dark:border-white/10 overflow-hidden">
        <div class="overflow-x-auto">
            <table class="w-full text-sm">
                <thead class="bg-gray-50 dark:bg-white/5 text-xs text-gray-500 dark:text-slate-400 uppercase">
                    <tr>
                        <th class="px-4 py-3 text-left">Report Name</th>
                        <th class="px-4 py-3 text-left hidden md:table-cell">Type</th>
                        <th class="px-4 py-3 text-left hidden sm:table-cell">Period</th>
                        <th class="px-4 py-3 text-left hidden lg:table-cell">Generated By</th>
                        <th class="px-4 py-3 text-center hidden sm:table-cell">Format</th>
                        <th class="px-4 py-3 text-center hidden sm:table-cell">Size</th>
                        <th class="px-4 py-3 text-center">Status</th>
                        <th class="px-4 py-3 text-center">Aksi</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-gray-100 dark:divide-white/5">
                    <?php $__empty_1 = true; $__currentLoopData = $reports ?? []; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $report): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); $__empty_1 = false; ?>
                        <tr class="hover:bg-gray-50 dark:hover:bg-white/5">
                            <td class="px-4 py-3">
                                <p class="font-medium text-gray-900 dark:text-white"><?php echo e($report->name); ?></p>
                                <p class="text-xs text-gray-500 dark:text-slate-400">
                                    <?php echo e(Str::limit($report->description ?? '', 50)); ?></p>
                            </td>
                            <td class="px-4 py-3 hidden md:table-cell">
                                <span
                                    class="inline-flex items-center px-2 py-1 text-xs font-medium rounded-lg bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400">
                                    <?php echo e(str_replace('_', ' ', ucfirst($report->report_type))); ?>

                                </span>
                            </td>
                            <td class="px-4 py-3 hidden sm:table-cell">
                                <p class="text-gray-900 dark:text-white">
                                    <?php echo e($report->from_date ? \Carbon\Carbon::parse($report->from_date)->format('d M Y') : '-'); ?>

                                </p>
                                <p class="text-xs text-gray-500 dark:text-slate-400">to
                                    <?php echo e($report->to_date ? \Carbon\Carbon::parse($report->to_date)->format('d M Y') : '-'); ?>

                                </p>
                            </td>
                            <td class="px-4 py-3 text-gray-600 dark:text-slate-300 hidden lg:table-cell">
                                <?php echo e($report->generatedBy ? $report->generatedBy->name : '-'); ?></td>
                            <td class="px-4 py-3 text-center hidden sm:table-cell">
                                <span
                                    class="inline-flex items-center px-2 py-1 text-xs font-medium rounded-lg bg-gray-100 text-gray-700 dark:bg-gray-700 dark:text-gray-300">
                                    <?php echo e(strtoupper($report->format ?? 'PDF')); ?>

                                </span>
                            </td>
                            <td class="px-4 py-3 text-center text-gray-600 dark:text-slate-300 hidden sm:table-cell">
                                <?php echo e($report->file_size ? number_format($report->file_size / 1024, 1) . ' KB' : '-'); ?>

                            </td>
                            <td class="px-4 py-3 text-center">
                                <?php if($report->status === 'completed'): ?>
                                    <span
                                        class="inline-flex items-center px-2 py-1 text-xs font-medium rounded-lg bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400">Completed</span>
                                <?php elseif($report->status === 'generating'): ?>
                                    <span
                                        class="inline-flex items-center px-2 py-1 text-xs font-medium rounded-lg bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400">Generating</span>
                                <?php elseif($report->status === 'failed'): ?>
                                    <span
                                        class="inline-flex items-center px-2 py-1 text-xs font-medium rounded-lg bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400">Failed</span>
                                <?php endif; ?>
                            </td>
                            <td class="px-4 py-3 text-center">
                                <div class="flex items-center justify-center gap-2">
                                    <?php if($report->status === 'completed'): ?>
                                        <a href="<?php echo e(route('healthcare.analytics.reports.download', $report)); ?>"
                                            class="p-1.5 text-green-600 hover:bg-green-50 dark:text-green-400 dark:hover:bg-green-900/30 rounded-lg"
                                            title="Download">
                                            <svg class="w-4 h-4" fill="none" stroke="currentColor"
                                                viewBox="0 0 24 24">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"
                                                    d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4">
                                                </path>
                                            </svg>
                                        </a>
                                        <a href="<?php echo e(route('healthcare.analytics.reports.show', $report)); ?>"
                                            class="p-1.5 text-blue-600 hover:bg-blue-50 dark:text-blue-400 dark:hover:bg-blue-900/30 rounded-lg"
                                            title="View">
                                            <svg class="w-4 h-4" fill="none" stroke="currentColor"
                                                viewBox="0 0 24 24">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"
                                                    d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"
                                                    d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z">
                                                </path>
                                            </svg>
                                        </a>
                                    <?php endif; ?>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); if ($__empty_1): ?>
                        <tr>
                            <td colspan="8" class="px-4 py-8 text-center text-gray-500 dark:text-slate-400">
                                <p>Belum ada report yang dibuat</p>
                            </td>
                        </tr>
                    <?php endif; ?>
                </tbody>
            </table>
        </div>

        <?php if(isset($reports) && $reports->hasPages()): ?>
            <div class="px-4 py-3 border-t border-gray-200 dark:border-white/10">
                <?php echo e($reports->links()); ?>

            </div>
        <?php endif; ?>
    </div>

    <?php $__env->startPush('scripts'); ?>
        <script>
            function exportReport(format) {
                const params = new URLSearchParams(window.location.search);
                params.set('format', format);
                window.location.href = window.location.pathname + '?' + params.toString();
            }
        </script>
    <?php $__env->stopPush(); ?>
 <?php echo $__env->renderComponent(); ?>
<?php endif; ?>
<?php if (isset($__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54)): ?>
<?php $attributes = $__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54; ?>
<?php unset($__attributesOriginal9ac128a9029c0e4701924bd2d73d7f54); ?>
<?php endif; ?>
<?php if (isset($__componentOriginal9ac128a9029c0e4701924bd2d73d7f54)): ?>
<?php $component = $__componentOriginal9ac128a9029c0e4701924bd2d73d7f54; ?>
<?php unset($__componentOriginal9ac128a9029c0e4701924bd2d73d7f54); ?>
<?php endif; ?>
<?php /**PATH E:\PROJEKU\qalcuityERP\resources\views\healthcare\analytics\reports.blade.php ENDPATH**/ ?>