<?php

namespace App\Models;

use App\Traits\BelongsToTenant;

use App\Traits\AuditsChanges;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;

class RevenuePosting extends Model
{
    use BelongsToTenant;
    use SoftDeletes, AuditsChanges;

    protected $fillable = [
        'tenant_id',
        'audit_batch_id',
        'posting_reference',
        'posting_date',
        'reservation_id',
        'room_number',
        'guest_id',
        'revenue_type',
        'description',
        'amount',
        'tax_amount',
        'total_amount',
        'status',
        'auto_generated',
        'created_by',
        'posted_at',
        'notes',
    ];

    protected function casts(): array
    {
        return [
            'posting_date' => 'date',
            'amount' => 'decimal:2',
            'tax_amount' => 'decimal:2',
            'total_amount' => 'decimal:2',
            'auto_generated' => 'boolean',
            'posted_at' => 'datetime',
        ];
    }

    public function tenant(): BelongsTo
    {
        return $this->belongsTo(Tenant::class);
    }

    public function auditBatch(): BelongsTo
    {
        return $this->belongsTo(NightAuditBatch::class, 'audit_batch_id');
    }

    public function reservation(): BelongsTo
    {
        return $this->belongsTo(Reservation::class);
    }

    public function guest(): BelongsTo
    {
        return $this->belongsTo(Guest::class);
    }

    public function createdBy(): BelongsTo
    {
        return $this->belongsTo(User::class, 'created_by');
    }

    /**
     * Generate unique posting reference
     */
    public static function generatePostingReference(): string
    {
        $date = now()->format('Ymd');
        $count = static::whereDate('created_at', today())->count() + 1;
        return "RP-{$date}-" . str_pad($count, 3, '0', STR_PAD_LEFT);
    }

    /**
     * Calculate total amount with tax
     */
    public function calculateTotal(): void
    {
        $this->total_amount = $this->amount + $this->tax_amount;
        $this->save();
    }

    /**
     * Post the revenue (mark as posted)
     */
    public function post(): void
    {
        $this->update([
            'status' => 'posted',
            'posted_at' => now(),
        ]);

        ActivityLog::record(
            'revenue_posted',
            "Posted revenue: {$this->description} - Rp " . number_format($this->total_amount, 0, ',', '.'),
            $this,
            ['posting_id' => $this->id]
        );
    }

    /**
     * Void the posting
     */
    public function void(string $reason = ''): void
    {
        $this->update([
            'status' => 'voided',
            'notes' => $reason,
        ]);

        ActivityLog::record(
            'revenue_voided',
            "Voided revenue posting: {$this->posting_reference}",
            $this,
            ['reason' => $reason]
        );
    }

    /**
     * Check if posting can be voided
     */
    public function canBeVoided(): bool
    {
        return $this->status === 'posted';
    }

    /**
     * Scope for auto-generated postings
     */
    public function scopeAutoGenerated($query)
    {
        return $query->where('auto_generated', true);
    }

    /**
     * Scope for manual postings
     */
    public function scopeManual($query)
    {
        return $query->where('auto_generated', false);
    }
}
