<?php

namespace App\Models;

use App\Traits\BelongsToTenant;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class WorkflowAction extends Model
{
    use BelongsToTenant;
    protected $fillable = [
        'tenant_id',
        'workflow_id',
        'action_type', // create_po, send_notification, update_record, etc
        'action_config', // JSON configuration
        'order',
        'condition', // Optional condition JSON
        'is_active',
    ];

    protected function casts(): array
    {
        return [
            'action_config' => 'array',
            'condition' => 'array',
            'order' => 'integer',
            'is_active' => 'boolean',
        ];
    }

    public function tenant(): BelongsTo
    {
        return $this->belongsTo(Tenant::class);
    }

    public function workflow(): BelongsTo
    {
        return $this->belongsTo(Workflow::class);
    }

    /**
     * Execute this action
     */
    public function execute(array $context = []): array
    {
        if (!$this->is_active) {
            return ['success' => true, 'message' => 'Action skipped (inactive)'];
        }

        // Check condition if exists
        if ($this->condition && !$this->evaluateCondition($context)) {
            return ['success' => true, 'message' => 'Condition not met'];
        }

        try {
            $result = match ($this->action_type) {
                'create_purchase_order' => $this->createPurchaseOrder($context),
                'send_whatsapp' => $this->sendWhatsApp($context),
                'send_email' => $this->sendEmail($context),
                'send_notification' => $this->sendNotification($context),
                'update_inventory' => $this->updateInventory($context),
                'calculate_bonus' => $this->calculateBonus($context),
                'create_invoice' => $this->createInvoice($context),
                'update_record' => $this->updateRecord($context),
                'webhook_call' => $this->callWebhook($context),
                default => throw new \Exception("Unknown action type: {$this->action_type}"),
            };

            return ['success' => true, 'result' => $result];

        } catch (\Exception $e) {
            return ['success' => false, 'error' => $e->getMessage()];
        }
    }

    /**
     * Evaluate condition
     */
    private function evaluateCondition(array $context): bool
    {
        // Simple condition evaluator
        // Example: {"field": "stock_quantity", "operator": "<", "value": 10}

        if (!$this->condition) {
            return true;
        }

        $field = $this->condition['field'] ?? null;
        $operator = $this->condition['operator'] ?? '=';
        $value = $this->condition['value'] ?? null;

        if (!$field || !isset($context[$field])) {
            return false;
        }

        $contextValue = $context[$field];

        return match ($operator) {
            '<' => $contextValue < $value,
            '<=' => $contextValue <= $value,
            '>' => $contextValue > $value,
            '>=' => $contextValue >= $value,
            '=' => $contextValue == $value,
            '!=' => $contextValue != $value,
            'contains' => str_contains((string) $contextValue, (string) $value),
            default => false,
        };
    }

    // ==================== ACTION IMPLEMENTATIONS ====================

    private function createPurchaseOrder(array $context): array
    {
        // Auto-create purchase order when stock is low
        $product = Product::find($context['product_id'] ?? null);

        if (!$product) {
            throw new \Exception('Product not found');
        }

        $supplier = Supplier::find($this->action_config['supplier_id'] ?? null);

        if (!$supplier) {
            throw new \Exception('Supplier not found');
        }

        $quantity = $this->action_config['quantity'] ?? 100;

        $po = PurchaseOrder::create([
            'tenant_id' => $this->tenant_id,
            'supplier_id' => $supplier->id,
            'order_number' => 'PO-AUTO-' . date('YmdHis'),
            'order_date' => now(),
            'status' => 'draft',
            'notes' => 'Auto-generated by workflow: ' . $this->workflow->name,
        ]);

        PurchaseOrderItem::create([
            'purchase_order_id' => $po->id,
            'product_id' => $product->id,
            'quantity' => $quantity,
            'unit_price' => $product->cost_price ?? 0,
        ]);

        return ['purchase_order_id' => $po->id, 'order_number' => $po->order_number];
    }

    private function sendWhatsApp(array $context): array
    {
        $phoneNumber = $this->action_config['phone_number'] ?? $context['phone'] ?? null;
        $message = $this->buildMessage($context);

        // Integration with WhatsApp API (Twilio, Wablas, etc)
        // This is a placeholder - implement actual WhatsApp integration

        return [
            'sent' => true,
            'phone' => $phoneNumber,
            'message_preview' => substr($message, 0, 50),
        ];
    }

    private function sendEmail(array $context): array
    {
        $to = $this->action_config['email'] ?? $context['email'] ?? null;
        $subject = $this->action_config['subject'] ?? 'Notification';
        $message = $this->buildMessage($context);

        \Illuminate\Support\Facades\Mail::raw($message, function ($mail) use ($to, $subject) {
            $mail->to($to)->subject($subject);
        });

        return ['sent' => true, 'email' => $to];
    }

    private function sendNotification(array $context): array
    {
        $userId = $this->action_config['user_id'] ?? $context['user_id'] ?? null;
        $title = $this->action_config['title'] ?? 'Notification';
        $message = $this->buildMessage($context);

        if ($userId) {
            ErpNotification::create([
                'tenant_id' => $this->tenant_id,
                'user_id' => $userId,
                'title' => $title,
                'message' => $message,
                'type' => 'workflow',
                'is_read' => false,
            ]);
        }

        return ['sent' => true, 'user_id' => $userId];
    }

    private function calculateBonus(array $context): array
    {
        $employeeId = $context['employee_id'] ?? null;
        $salesAmount = $context['sales_amount'] ?? 0;
        $target = $this->action_config['target'] ?? 0;
        $bonusPercentage = $this->action_config['bonus_percentage'] ?? 5;

        if ($salesAmount > $target) {
            $bonus = ($salesAmount - $target) * ($bonusPercentage / 100);

            // Create bonus record or add to payroll
            return [
                'bonus_calculated' => true,
                'amount' => $bonus,
                'employee_id' => $employeeId,
            ];
        }

        return ['bonus_calculated' => false, 'reason' => 'Target not exceeded'];
    }

    private function updateInventory(array $context): array
    {
        $productId = $context['product_id'] ?? null;
        $adjustment = $this->action_config['adjustment'] ?? 0;

        $product = Product::find($productId);
        if ($product) {
            $product->stock += $adjustment;
            $product->save();
        }

        return ['updated' => true, 'product_id' => $productId];
    }

    private function createInvoice(array $context): array
    {
        // Auto-create invoice logic
        return ['invoice_created' => true];
    }

    private function updateRecord(array $context): array
    {
        // Generic record update
        return ['updated' => true];
    }

    private function callWebhook(array $context): array
    {
        $url = $this->action_config['url'] ?? null;

        if (!$url) {
            throw new \Exception('Webhook URL not configured');
        }

        $response = \Illuminate\Support\Facades\Http::post($url, [
            'event' => $this->workflow->name,
            'context' => $context,
            'timestamp' => now()->toIso8601String(),
        ]);

        return ['webhook_called' => true, 'status' => $response->status()];
    }

    private function buildMessage(array $context): string
    {
        $template = $this->action_config['message_template'] ?? 'Notification from workflow';

        // Replace placeholders like {{product_name}} with context values
        foreach ($context as $key => $value) {
            $template = str_replace("{{{$key}}}", $value, $template);
        }

        return $template;
    }
}
