<x-app-layout>
    <x-slot name="header">Healthcare Reports</x-slot>

    @php $tid = auth()->user()->tenant_id; @endphp

    {{-- Filters --}}
    <div class="bg-white rounded-2xl border border-gray-200 mb-6">
        <div class="p-4">
            <form method="GET" class="flex flex-col lg:flex-row gap-3">
                <select name="report_type"
                    class="px-3 py-2 text-sm rounded-xl border border-gray-200 bg-gray-50 text-gray-900">
                    <option value="">Semua Report</option>
                    <option value="patient_statistics" @selected(request('report_type') === 'patient_statistics')>Patient Statistics</option>
                    <option value="revenue_report" @selected(request('report_type') === 'revenue_report')>Revenue Report</option>
                    <option value="department_performance" @selected(request('report_type') === 'department_performance')>Department Performance</option>
                    <option value="doctor_productivity" @selected(request('report_type') === 'doctor_productivity')>Doctor Productivity</option>
                    <option value="inventory_status" @selected(request('report_type') === 'inventory_status')>Inventory Status</option>
                </select>
                <div>
                    <input type="date" name="from" value="{{ request('from') }}"
                        class="px-3 py-2 text-sm rounded-xl border border-gray-200 bg-gray-50 text-gray-900"
                        placeholder="Dari Tanggal">
                </div>
                <div>
                    <input type="date" name="to" value="{{ request('to') }}"
                        class="px-3 py-2 text-sm rounded-xl border border-gray-200 bg-gray-50 text-gray-900"
                        placeholder="Sampai Tanggal">
                </div>
                <button type="submit" class="px-4 py-2 text-sm bg-blue-600 text-white rounded-xl hover:bg-blue-700">
                    Filter
                </button>
                <div class="flex items-end gap-2">
                    <button type="button" onclick="exportReport('pdf')"
                        class="px-4 py-2 text-sm bg-red-600 text-white rounded-xl hover:bg-red-700">
                        Export PDF
                    </button>
                    <button type="button" onclick="exportReport('excel')"
                        class="px-4 py-2 text-sm bg-green-600 text-white rounded-xl hover:bg-green-700">
                        Export Excel
                    </button>
                </div>
            </form>
        </div>
    </div>

    {{-- Reports Table --}}
    <div class="bg-white rounded-2xl border border-gray-200 overflow-hidden">
        <div class="overflow-x-auto">
            <table class="w-full text-sm">
                <thead class="bg-gray-50 text-xs text-gray-500 uppercase">
                    <tr>
                        <th class="px-4 py-3 text-left">Report Name</th>
                        <th class="px-4 py-3 text-left hidden md:table-cell">Type</th>
                        <th class="px-4 py-3 text-left hidden sm:table-cell">Period</th>
                        <th class="px-4 py-3 text-left hidden lg:table-cell">Generated By</th>
                        <th class="px-4 py-3 text-center hidden sm:table-cell">Format</th>
                        <th class="px-4 py-3 text-center hidden sm:table-cell">Size</th>
                        <th class="px-4 py-3 text-center">Status</th>
                        <th class="px-4 py-3 text-center">Aksi</th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-gray-100">
                    @forelse($reports ?? [] as $report)
                        <tr class="hover:bg-gray-50">
                            <td class="px-4 py-3">
                                <p class="font-medium text-gray-900">{{ $report->name }}</p>
                                <p class="text-xs text-gray-500">
                                    {{ Str::limit($report->description ?? '', 50) }}</p>
                            </td>
                            <td class="px-4 py-3 hidden md:table-cell">
                                <span
                                    class="inline-flex items-center px-2 py-1 text-xs font-medium rounded-lg bg-blue-100 text-blue-700">
                                    {{ str_replace('_', ' ', ucfirst($report->report_type)) }}
                                </span>
                            </td>
                            <td class="px-4 py-3 hidden sm:table-cell">
                                <p class="text-gray-900">
                                    {{ $report->from_date ? \Carbon\Carbon::parse($report->from_date)->format('d M Y') : '-' }}
                                </p>
                                <p class="text-xs text-gray-500">to
                                    {{ $report->to_date ? \Carbon\Carbon::parse($report->to_date)->format('d M Y') : '-' }}
                                </p>
                            </td>
                            <td class="px-4 py-3 text-gray-600 hidden lg:table-cell">
                                {{ $report->generatedBy ? $report->generatedBy->name : '-' }}</td>
                            <td class="px-4 py-3 text-center hidden sm:table-cell">
                                <span
                                    class="inline-flex items-center px-2 py-1 text-xs font-medium rounded-lg bg-gray-100 text-gray-700">
                                    {{ strtoupper($report->format ?? 'PDF') }}
                                </span>
                            </td>
                            <td class="px-4 py-3 text-center text-gray-600 hidden sm:table-cell">
                                {{ $report->file_size ? number_format($report->file_size / 1024, 1) . ' KB' : '-' }}
                            </td>
                            <td class="px-4 py-3 text-center">
                                @if ($report->status === 'completed')
                                    <span
                                        class="inline-flex items-center px-2 py-1 text-xs font-medium rounded-lg bg-green-100 text-green-700">Completed</span>
                                @elseif($report->status === 'generating')
                                    <span
                                        class="inline-flex items-center px-2 py-1 text-xs font-medium rounded-lg bg-blue-100 text-blue-700">Generating</span>
                                @elseif($report->status === 'failed')
                                    <span
                                        class="inline-flex items-center px-2 py-1 text-xs font-medium rounded-lg bg-red-100 text-red-700">Failed</span>
                                @endif
                            </td>
                            <td class="px-4 py-3 text-center">
                                <div class="flex items-center justify-center gap-2">
                                    @if ($report->status === 'completed')
                                        <a href="{{ route('healthcare.analytics.reports.download', $report) }}"
                                            class="p-1.5 text-green-600 hover:bg-green-50 rounded-lg"
                                            title="Download">
                                            <svg class="w-4 h-4" fill="none" stroke="currentColor"
                                                viewBox="0 0 24 24">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"
                                                    d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4">
                                                </path>
                                            </svg>
                                        </a>
                                        <a href="{{ route('healthcare.analytics.reports.show', $report) }}"
                                            class="p-1.5 text-blue-600 hover:bg-blue-50 rounded-lg"
                                            title="View">
                                            <svg class="w-4 h-4" fill="none" stroke="currentColor"
                                                viewBox="0 0 24 24">
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"
                                                    d="M15 12a3 3 0 11-6 0 3 3 0 016 0z"></path>
                                                <path stroke-linecap="round" stroke-linejoin="round" stroke-width="1.5"
                                                    d="M2.458 12C3.732 7.943 7.523 5 12 5c4.478 0 8.268 2.943 9.542 7-1.274 4.057-5.064 7-9.542 7-4.477 0-8.268-2.943-9.542-7z">
                                                </path>
                                            </svg>
                                        </a>
                                    @endif
                                </div>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="8" class="px-4 py-8 text-center text-gray-500">
                                <p>Belum ada report yang dibuat</p>
                            </td>
                        </tr>
                    @endforelse
                </tbody>
            </table>
        </div>

        @if (isset($reports) && $reports->hasPages())
            <div class="px-4 py-3 border-t border-gray-200">
                {{ $reports->links() }}
            </div>
        @endif
    </div>

    @push('scripts')
        <script>
            function exportReport(format) {
                const params = new URLSearchParams(window.location.search);
                params.set('format', format);
                window.location.href = window.location.pathname + '?' + params.toString();
            }
        </script>
    @endpush
</x-app-layout>
